# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-03 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default='89bb1b8c-a2eb-4b8f-9ea5-ac34f0425df0', max_length=36)),
            ],
        ),
    ]
