# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-03 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import twitter.models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_validationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='validationtoken',
            name='token',
            field=models.CharField(default=twitter.models.generate_token, max_length=36),
        ),
    ]
