# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20160829_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_validated',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
