# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-03 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20160903_0947'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='validationtoken',
            unique_together=set([('email', 'token')]),
        ),
    ]
