# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import twitter.models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_user_email_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=twitter.models.get_hash_token, max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='validationtoken',
            unique_together=set([('email', 'token')]),
        ),
    ]
